"""empty message

Revision ID: d80daed11bf7
Revises: e04370397adc
Create Date: 2025-05-08 08:01:22.567322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80daed11bf7'
down_revision = 'e04370397adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites')
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('climate', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('surface_water', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('population', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('population')
        batch_op.drop_column('surface_water')
        batch_op.drop_column('terrain')
        batch_op.drop_column('gravity')
        batch_op.drop_column('diameter')
        batch_op.drop_column('climate')
        batch_op.drop_column('name')

    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.drop_table('favorite_planets')
    op.drop_table('favorite_people')
    # ### end Alembic commands ###
