"""empty message

Revision ID: e04370397adc
Revises: 65865f17e3f7
Create Date: 2025-05-07 12:02:38.127908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04370397adc'
down_revision = '65865f17e3f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('height', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('mass', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('birth_year')
        batch_op.drop_column('mass')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('height')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
